# generated by datamodel-codegen:
#   filename:  full.openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    confloat,
    conint,
    constr,
)


class Actor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')


class ApprovalStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'
    expired = 'expired'
    cancelled = 'cancelled'


class ApprovalType(StrEnum):
    write_execution = 'write_execution'
    secret_access = 'secret_access'
    command_exception = 'command_exception'


class ArtifactType(StrEnum):
    patch = 'patch'
    log = 'log'
    report = 'report'
    screenshot = 'screenshot'
    trace_snapshot = 'trace_snapshot'
    test_report = 'test_report'
    file = 'file'
    summary = 'summary'
    evidence = 'evidence'
    command_output = 'command_output'


class AuthenticatedUserModel(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    display_name: str = Field(..., title='Display Name')
    email: str = Field(..., title='Email')
    id: str = Field(..., title='Id')
    is_platform_admin: bool = Field(..., title='Is Platform Admin')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class BreakGlassKind(StrEnum):
    incident_response = 'incident_response'
    maintenance = 'maintenance'
    operator_override = 'operator_override'


class BreakGlassReason(BaseModel):
    approved_by: str = Field(..., title='Approved By')
    expires_at: str | None = Field(None, title='Expires At')
    kind: BreakGlassKind
    reason: str = Field(..., title='Reason')
    ticket_id: str | None = Field(None, title='Ticket Id')


class ContextLevel(StrEnum):
    L0 = 'L0'
    L1 = 'L1'
    L2 = 'L2'
    L3 = 'L3'


class Correlation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attemptId: str | None = Field(None, title='Attemptid')
    projectId: str = Field(..., title='Projectid')
    runId: str = Field(..., title='Runid')
    taskId: str = Field(..., title='Taskid')


class CreateProjectRequest(BaseModel):
    default_branch: constr(min_length=1, max_length=120) | None = Field(
        'main', title='Default Branch'
    )
    description: constr(max_length=4000) | None = Field(None, title='Description')
    name: constr(min_length=2, max_length=160) = Field(..., title='Name')
    root_path: constr(min_length=1, max_length=1024) = Field(..., title='Root Path')


class CreateSessionRequest(BaseModel):
    email: EmailStr = Field(..., title='Email')
    password: constr(min_length=1, max_length=256) = Field(..., title='Password')


class DispatchControl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_id: str | None = Field(None, title='Attempt Id')
    heartbeat_interval_seconds: conint(ge=1) | None = Field(
        30, title='Heartbeat Interval Seconds'
    )
    idempotency_key: str = Field(..., title='Idempotency Key')
    replay_of_attempt_id: str | None = Field(None, title='Replay Of Attempt Id')
    timeout_seconds: conint(ge=1) | None = Field(1800, title='Timeout Seconds')


class EventType(StrEnum):
    workflow_started = 'workflow.started'
    workflow_completed = 'workflow.completed'
    workflow_failed = 'workflow.failed'
    workflow_retrying = 'workflow.retrying'
    workflow_waiting_approval = 'workflow.waiting_approval'
    task_claimed = 'task.claimed'
    task_running = 'task.running'
    task_verifying = 'task.verifying'
    task_completed = 'task.completed'
    task_failed = 'task.failed'
    task_heartbeat = 'task.heartbeat'
    task_reclaimed = 'task.reclaimed'
    task_graph_updated = 'task.graph.updated'
    task_todo_updated = 'task.todo.updated'
    approval_requested = 'approval.requested'
    approval_resolved = 'approval.resolved'
    notification_sent = 'notification.sent'
    artifact_linked = 'artifact.linked'
    memory_recalled = 'memory.recalled'
    memory_written = 'memory.written'
    runtime_graph_interrupted = 'runtime.graph.interrupted'
    runtime_graph_completed = 'runtime.graph.completed'
    worker_health_reported = 'worker.health.reported'


class EvidenceKind(StrEnum):
    artifact = 'artifact'
    memory = 'memory'
    verification = 'verification'
    approval = 'approval'
    provenance = 'provenance'


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: EvidenceKind
    ref: str = Field(..., title='Ref')
    summary: str | None = Field(None, title='Summary')


class EvidenceRefView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    href: str = Field(..., title='Href')
    id: str = Field(..., title='Id')
    label: str = Field(..., title='Label')
    type: EvidenceKind


class ExecutionProvenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_id: str = Field(..., title='Attempt Id')
    executor: str = Field(..., title='Executor')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    model: str | None = Field(None, title='Model')
    operator: str | None = Field(None, title='Operator')
    provider_request_id: str = Field(..., title='Provider Request Id')
    trigger: str = Field(..., title='Trigger')
    workspace_ref: str = Field(..., title='Workspace Ref')


class ExecutionStatus(StrEnum):
    succeeded = 'succeeded'
    failed = 'failed'
    waiting_approval = 'waiting_approval'
    cancelled = 'cancelled'
    timed_out = 'timed_out'


class ExecutorCapability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    executor: str = Field(..., title='Executor')
    supports_screenshots: bool = Field(..., title='Supports Screenshots')
    supports_tools: bool = Field(..., title='Supports Tools')
    supports_verify: bool = Field(..., title='Supports Verify')
    supports_write: bool = Field(..., title='Supports Write')


class FailureKind(StrEnum):
    retryable = 'retryable'
    terminal = 'terminal'


class IterationStatus(StrEnum):
    planned = 'planned'
    active = 'active'
    completed = 'completed'


class LogEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: str = Field(..., title='Message')
    stream: str = Field(..., title='Stream')
    timestamp: AwareDatetime | None = Field(None, title='Timestamp')


class MembershipCountSummaryModel(BaseModel):
    admin: int = Field(..., title='Admin')
    maintainer: int = Field(..., title='Maintainer')
    reviewer: int = Field(..., title='Reviewer')
    viewer: int = Field(..., title='Viewer')


class MembershipStatus(StrEnum):
    active = 'active'
    invited = 'invited'
    suspended = 'suspended'


class MemoryHitView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    externalRef: str | None = Field(None, title='Externalref')
    id: str = Field(..., title='Id')
    namespace: str = Field(..., title='Namespace')
    recallCount: int | None = Field(0, title='Recallcount')
    retentionPolicy: str | None = Field('retain_for_project', title='Retentionpolicy')
    score: float = Field(..., title='Score')
    staleAt: str | None = Field(None, title='Staleat')
    summary: str = Field(..., title='Summary')
    supersedesRecordId: str | None = Field(None, title='Supersedesrecordid')
    version: int | None = Field(1, title='Version')


class MemoryHitsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[MemoryHitView] = Field(..., title='Items')


class MemoryType(StrEnum):
    long_term_knowledge = 'long_term_knowledge'
    project_fact = 'project_fact'
    lesson = 'lesson'


class NotificationDeliveryRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: str = Field(..., title='Body')
    created_at: AwareDatetime = Field(..., title='Created At')
    delivery_channel: str = Field(..., title='Delivery Channel')
    delivery_id: str = Field(..., title='Delivery Id')
    delivery_status: str = Field(..., title='Delivery Status')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    provider_message_id: str | None = Field(None, title='Provider Message Id')
    receipt_id: str = Field(..., title='Receipt Id')
    sent_at: AwareDatetime = Field(..., title='Sent At')
    source_channel: str = Field(..., title='Source Channel')
    title: str = Field(..., title='Title')
    trace_id: str = Field(..., title='Trace Id')
    workflow_run_id: str = Field(..., title='Workflow Run Id')


class NotificationDeliveryStatusUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    delivery_status: constr(min_length=1, max_length=64) = Field(
        ..., title='Delivery Status'
    )
    metadata_patch: dict[str, Any] | None = Field(None, title='Metadata Patch')
    provider_message_id: str | None = Field(None, title='Provider Message Id')


class PlanStatus(StrEnum):
    draft = 'draft'
    ready = 'ready'
    archived = 'archived'


class PlanSummaryByStatusModel(BaseModel):
    archived: int = Field(..., title='Archived')
    draft: int = Field(..., title='Draft')
    ready: int = Field(..., title='Ready')


class PlanSummaryRecordModel(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    id: str = Field(..., title='Id')
    iteration_id: str | None = Field(..., title='Iteration Id')
    status: PlanStatus
    title: str = Field(..., title='Title')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class PlanSummaryResponse(BaseModel):
    by_status: PlanSummaryByStatusModel
    latest_plan: PlanSummaryRecordModel | None
    schema_version: str | None = Field('2026-04-19.1', title='Schema Version')
    total_plans: int = Field(..., title='Total Plans')


class ProjectRole(StrEnum):
    admin = 'admin'
    maintainer = 'maintainer'
    reviewer = 'reviewer'
    viewer = 'viewer'


class ProjectStatus(StrEnum):
    active = 'active'
    archived = 'archived'


class ProvenanceRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contentHash: str = Field(..., title='Contenthash')
    correlation: Correlation
    createdAt: str = Field(..., title='Createdat')
    producer: str = Field(..., title='Producer')
    source: str = Field(..., title='Source')


class RegisterUserRequest(BaseModel):
    display_name: constr(min_length=1, max_length=120) = Field(
        ..., title='Display Name'
    )
    email: EmailStr = Field(..., title='Email')
    password: constr(min_length=8, max_length=256) = Field(..., title='Password')


class RequestOptions(BaseModel):
    full_access: BreakGlassReason | None = None


class RetentionPolicy(StrEnum):
    retain_for_run = 'retain_for_run'
    retain_for_project = 'retain_for_project'
    retain_permanent = 'retain_permanent'
    decay_30d = 'decay_30d'
    decay_90d = 'decay_90d'


class RiskLevel(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class SecretSource(StrEnum):
    broker = 'broker'
    operator = 'operator'
    environment = 'environment'


class SecretUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expires_at: AwareDatetime | None = Field(None, title='Expires At')
    name: str = Field(..., title='Name')
    scope: str = Field(..., title='Scope')
    source: SecretSource


class SecuritySummaryView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approvalRequired: bool = Field(..., title='Approvalrequired')
    scope: str = Field(..., title='Scope')
    usedSecret: bool = Field(..., title='Usedsecret')
    writeAllowed: bool = Field(..., title='Writeallowed')


class SessionMembershipModel(BaseModel):
    project_id: str = Field(..., title='Project Id')
    project_name: str = Field(..., title='Project Name')
    role: ProjectRole
    status: MembershipStatus


class SessionRecordModel(BaseModel):
    expires_at: AwareDatetime = Field(..., title='Expires At')
    id: str = Field(..., title='Id')
    token: str = Field(..., title='Token')


class TaskGraphEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: str = Field(..., title='Kind')
    source_task_id: str = Field(..., title='Source Task Id')
    target_task_id: str = Field(..., title='Target Task Id')


class TaskInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str = Field(..., title='Description')
    executor: str = Field(..., title='Executor')
    expected_artifact_types: list[ArtifactType] | None = Field(
        None, title='Expected Artifact Types'
    )
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    priority: str | None = Field('normal', title='Priority')
    run_id: str = Field(..., title='Run Id')
    task_id: str = Field(..., title='Task Id')
    title: str = Field(..., title='Title')


class TaskStatus(StrEnum):
    queued = 'queued'
    claimed = 'claimed'
    running = 'running'
    verifying = 'verifying'
    waiting_approval = 'waiting_approval'
    retrying = 'retrying'
    completed = 'completed'
    failed = 'failed'
    reclaimed = 'reclaimed'
    cancelled = 'cancelled'


class TaskTodoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str | None = Field(None, title='Detail')
    id: str = Field(..., title='Id')
    status: str | None = Field('queued', title='Status')
    title: str = Field(..., title='Title')


class TimelineEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_id: str | None = Field(None, title='Attempt Id')
    event_type: EventType
    label: str = Field(..., title='Label')
    occurred_at: str = Field(..., title='Occurred At')
    sequence: int = Field(..., title='Sequence')
    summary: str | None = Field(None, title='Summary')
    task_id: str | None = Field(None, title='Task Id')
    trace_id: str = Field(..., title='Trace Id')


class TimelineReadModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: list[TimelineEntry] | None = Field(None, title='Entries')
    workflow_run_id: str = Field(..., title='Workflow Run Id')


class UpdateProjectRequest(BaseModel):
    default_branch: constr(min_length=1, max_length=120) | None = Field(
        None, title='Default Branch'
    )
    description: constr(max_length=4000) | None = Field(None, title='Description')
    name: constr(min_length=2, max_length=160) | None = Field(None, title='Name')
    root_path: constr(min_length=1, max_length=1024) | None = Field(
        None, title='Root Path'
    )
    status: ProjectStatus | None = None


class ValidationError(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class VerificationCheckView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    detail: str = Field(..., title='Detail')
    label: str = Field(..., title='Label')
    status: str = Field(..., title='Status')


class VerificationCommandResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: str = Field(..., title='Command')
    exit_code: int = Field(..., title='Exit Code')
    output: str = Field(..., title='Output')
    passed: bool = Field(..., title='Passed')


class VerificationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    passed: bool = Field(..., title='Passed')
    results: list[VerificationCommandResult] | None = Field(None, title='Results')
    summary: str = Field(..., title='Summary')


class VerificationView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checks: list[VerificationCheckView] | None = Field(None, title='Checks')
    summary: str = Field(..., title='Summary')
    verdict: str = Field(..., title='Verdict')


class VerifyCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: str = Field(..., title='Command')
    id: str = Field(..., title='Id')
    required: bool | None = Field(True, title='Required')


class WorkerHealthStatus(StrEnum):
    healthy = 'healthy'
    degraded = 'degraded'
    unhealthy = 'unhealthy'


class WorkflowName(StrEnum):
    project_import = 'project.import'
    project_audit = 'project.audit'
    project_planning = 'project.planning'
    task_execution = 'task.execution'
    project_improvement = 'project.improvement'


class WorkflowSimulationOptions(BaseModel):
    approval_task_ids: list[str] | None = Field(None, title='Approval Task Ids')
    interrupt_task_ids: list[str] | None = Field(None, title='Interrupt Task Ids')
    reclaim_task_ids: list[str] | None = Field(None, title='Reclaim Task Ids')
    retry_task_ids: list[str] | None = Field(None, title='Retry Task Ids')
    terminal_failure_task_ids: list[str] | None = Field(
        None, title='Terminal Failure Task Ids'
    )


class WorkflowTaskSpec(BaseModel):
    depends_on: list[str] | None = Field(None, title='Depends On')
    executor_name: str | None = Field(None, title='Executor Name')
    executor_summary: str | None = Field(None, title='Executor Summary')
    graph_kind: str = Field(..., title='Graph Kind')
    requires_approval: bool | None = Field(False, title='Requires Approval')
    task_id: str = Field(..., title='Task Id')
    title: str = Field(..., title='Title')


class WorkspaceMode(StrEnum):
    read_only = 'read_only'
    worktree = 'worktree'
    direct = 'direct'


class ApprovalDetailView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    correlation: Correlation
    expiresAt: str | None = Field(None, title='Expiresat')
    id: str = Field(..., title='Id')
    reason: str = Field(..., title='Reason')
    relatedArtifacts: list[str] | None = Field(None, title='Relatedartifacts')
    requestedAt: str = Field(..., title='Requestedat')
    requestedBy: Actor
    resolutionNote: str | None = Field(None, title='Resolutionnote')
    riskLevel: RiskLevel
    schemaVersion: str | None = Field('2026-04-19.execution.v1', title='Schemaversion')
    status: ApprovalStatus
    title: str = Field(..., title='Title')
    type: str = Field(..., title='Type')


class ApprovalResolutionPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved_write_paths: list[str] | None = Field(None, title='Approved Write Paths')
    decision: ApprovalStatus
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    reason: str = Field(..., title='Reason')


class ApprovalSummaryView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    correlation: Correlation
    id: str = Field(..., title='Id')
    reason: str = Field(..., title='Reason')
    requestedAt: str = Field(..., title='Requestedat')
    requestedBy: Actor
    riskLevel: RiskLevel
    schemaVersion: str | None = Field('2026-04-19.execution.v1', title='Schemaversion')
    status: ApprovalStatus
    title: str = Field(..., title='Title')
    type: str = Field(..., title='Type')


class ArtifactDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_type: ArtifactType
    content_hash: str = Field(..., title='Content Hash')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    path: str = Field(..., title='Path')
    producer: str = Field(..., title='Producer')
    provenance: ExecutionProvenance
    retention_policy: str | None = Field('retain_for_run', title='Retention Policy')
    summary: str | None = Field(None, title='Summary')
    workspace_ref: str = Field(..., title='Workspace Ref')


class ArtifactView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str = Field(..., title='Content')
    id: str = Field(..., title='Id')
    mimeType: str = Field(..., title='Mimetype')
    preview: str = Field(..., title='Preview')
    provenance: ProvenanceRecord
    schemaVersion: str | None = Field('2026-04-19.execution.v1', title='Schemaversion')
    title: str = Field(..., title='Title')
    type: str = Field(..., title='Type')


class AttemptRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_id: str = Field(..., title='Attempt Id')
    ended_at: str | None = Field(None, title='Ended At')
    event_sequence: list[int] | None = Field(None, title='Event Sequence')
    started_at: str | None = Field(None, title='Started At')
    status: TaskStatus | None = None
    task_id: str = Field(..., title='Task Id')


class ContextBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: str = Field(..., title='Body')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    level: ContextLevel
    source: str = Field(..., title='Source')
    title: str = Field(..., title='Title')
    truncated: bool | None = Field(False, title='Truncated')


class ContextBuilderInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_refs: list[EvidenceRef] = Field(..., title='Evidence Refs')
    memory_recall: list[str] = Field(..., title='Memory Recall')
    project_facts: list[str] = Field(..., title='Project Facts')
    recent_attempts: list[str] = Field(..., title='Recent Attempts')
    security_summary: str = Field(..., title='Security Summary')
    task_core: str = Field(..., title='Task Core')
    task_id: str = Field(..., title='Task Id')
    workflow_summary: str = Field(..., title='Workflow Summary')


class ContextBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[ContextBlock] = Field(..., title='Blocks')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    schema_version: str | None = Field(
        '2026-04-19.execution.v1', title='Schema Version'
    )
    task_id: str = Field(..., title='Task Id')


class ContextSkill(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: str = Field(..., title='Body')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    skill_id: str = Field(..., title='Skill Id')
    source: str | None = Field('context.skill', title='Source')
    title: str = Field(..., title='Title')


class EvidenceSummaryView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifactIds: list[str] | None = Field(None, title='Artifactids')
    attemptId: str = Field(..., title='Attemptid')
    evidenceRefs: list[EvidenceRefView] | None = Field(None, title='Evidencerefs')
    memoryHits: list[MemoryHitView] | None = Field(None, title='Memoryhits')
    schemaVersion: str | None = Field('2026-04-19.execution.v1', title='Schemaversion')
    verification: VerificationView | None = None


class ExecutorAttemptView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    correlation: Correlation
    evidenceRefs: list[EvidenceRefView] | None = Field(None, title='Evidencerefs')
    executor: str = Field(..., title='Executor')
    finishedAt: str = Field(..., title='Finishedat')
    id: str = Field(..., title='Id')
    memoryHits: list[MemoryHitView] | None = Field(None, title='Memoryhits')
    schemaVersion: str | None = Field('2026-04-19.execution.v1', title='Schemaversion')
    security: SecuritySummaryView
    startedAt: str = Field(..., title='Startedat')
    summary: str = Field(..., title='Summary')
    verification: VerificationView


class ExecutorCapabilitiesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ExecutorCapability] = Field(..., title='Items')


class FailureInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: str = Field(..., title='Category')
    detail: dict[str, Any] | None = Field(None, title='Detail')
    kind: FailureKind
    reason: str = Field(..., title='Reason')
    retry_after_seconds: conint(ge=1) | None = Field(None, title='Retry After Seconds')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class IterationRecordModel(BaseModel):
    created_at: AwareDatetime = Field(..., title='Created At')
    id: str = Field(..., title='Id')
    project_id: str = Field(..., title='Project Id')
    sequence_number: int = Field(..., title='Sequence Number')
    status: IterationStatus
    title: str = Field(..., title='Title')
    updated_at: AwareDatetime = Field(..., title='Updated At')


class MemoryWriteCandidate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content_hash: str = Field(..., title='Content Hash')
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    external_ref: str = Field(..., title='External Ref')
    force: bool | None = Field(False, title='Force')
    iteration_id: str | None = Field(None, title='Iteration Id')
    memory_type: MemoryType
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    namespace: str | None = Field(None, title='Namespace')
    project_id: str = Field(..., title='Project Id')
    quality_score: confloat(ge=0.0, le=1.0) = Field(..., title='Quality Score')
    retention_policy: RetentionPolicy | None = 'retain_for_project'
    summary: str = Field(..., title='Summary')
    supersedes_record_id: str | None = Field(None, title='Supersedes Record Id')


class NotificationDeliveryListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[NotificationDeliveryRecord] | None = Field(None, title='Items')


class PermissionPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_write_paths: list[str] | None = Field(None, title='Allowed Write Paths')
    command_allowlist: list[str] | None = Field(None, title='Command Allowlist')
    command_denylist: list[str] | None = Field(None, title='Command Denylist')
    require_manual_approval_for_write: bool | None = Field(
        True, title='Require Manual Approval For Write'
    )
    secret_broker_enabled: bool | None = Field(False, title='Secret Broker Enabled')
    workspace_allowlist: list[str] | None = Field(None, title='Workspace Allowlist')
    workspace_mode: WorkspaceMode | None = 'read_only'


class ProjectDetailResponse(BaseModel):
    active_iteration_count: int = Field(..., title='Active Iteration Count')
    active_plan_count: int = Field(..., title='Active Plan Count')
    can_archive: bool = Field(..., title='Can Archive')
    can_edit: bool = Field(..., title='Can Edit')
    created_at: AwareDatetime = Field(..., title='Created At')
    current_user_role: ProjectRole | None
    default_branch: str = Field(..., title='Default Branch')
    description: str | None = Field(..., title='Description')
    id: str = Field(..., title='Id')
    membership_counts: MembershipCountSummaryModel
    name: str = Field(..., title='Name')
    root_path: str = Field(..., title='Root Path')
    slug: str = Field(..., title='Slug')
    status: ProjectStatus
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ProjectListItemModel(BaseModel):
    active_iteration_count: int = Field(..., title='Active Iteration Count')
    active_plan_count: int = Field(..., title='Active Plan Count')
    created_at: AwareDatetime = Field(..., title='Created At')
    current_user_role: ProjectRole | None
    default_branch: str = Field(..., title='Default Branch')
    description: str | None = Field(..., title='Description')
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    root_path: str = Field(..., title='Root Path')
    slug: str = Field(..., title='Slug')
    status: ProjectStatus
    updated_at: AwareDatetime = Field(..., title='Updated At')


class ProjectPaginationModel(BaseModel):
    page: int = Field(..., title='Page')
    page_size: int = Field(..., title='Page Size')
    sort_by: str = Field(..., title='Sort By')
    sort_order: str = Field(..., title='Sort Order')
    status_filter: ProjectStatus | None
    total_items: int = Field(..., title='Total Items')
    total_pages: int = Field(..., title='Total Pages')


class SessionContextResponse(BaseModel):
    memberships: list[SessionMembershipModel] = Field(..., title='Memberships')
    schema_version: str | None = Field('2026-04-19.1', title='Schema Version')
    session: SessionRecordModel
    user: AuthenticatedUserModel


class TaskGraphNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocked_reason: str | None = Field(None, title='Blocked Reason')
    executor_summary: str | None = Field(None, title='Executor Summary')
    status: TaskStatus | None = None
    task_id: str = Field(..., title='Task Id')
    title: str = Field(..., title='Title')
    todo_items: list[TaskTodoItem] | None = Field(None, title='Todo Items')


class TaskGraphReadModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    edges: list[TaskGraphEdge] | None = Field(None, title='Edges')
    nodes: list[TaskGraphNode] | None = Field(None, title='Nodes')
    workflow_run_id: str = Field(..., title='Workflow Run Id')


class WorkerHealthReadModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    active_workflow_names: list[WorkflowName] | None = Field(
        None, title='Active Workflow Names'
    )
    detail: str | None = Field(None, title='Detail')
    last_seen_at: str = Field(..., title='Last Seen At')
    status: WorkerHealthStatus
    task_queue: str = Field(..., title='Task Queue')
    worker_id: str = Field(..., title='Worker Id')


class WorkflowRequest(BaseModel):
    initiated_by: str = Field(..., title='Initiated By')
    lease_timeout_seconds: int | None = Field(30, title='Lease Timeout Seconds')
    max_attempts: int | None = Field(2, title='Max Attempts')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')
    objective: str = Field(..., title='Objective')
    project_id: str = Field(..., title='Project Id')
    request_options: RequestOptions | None = None
    require_manual_approval: bool | None = Field(False, title='Require Manual Approval')
    signal_timeout_seconds: int | None = Field(300, title='Signal Timeout Seconds')
    simulation: WorkflowSimulationOptions | None = None
    tasks: list[WorkflowTaskSpec] | None = Field(None, title='Tasks')
    trace_id: str = Field(..., title='Trace Id')
    workflow_run_id: str = Field(..., title='Workflow Run Id')


class WorkspaceInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_commit_sha: str | None = Field(None, title='Base Commit Sha')
    iteration_id: str | None = Field(None, title='Iteration Id')
    mode: WorkspaceMode | None = 'read_only'
    project_id: str = Field(..., title='Project Id')
    root_path: str = Field(..., title='Root Path')
    workspace_ref: str = Field(..., title='Workspace Ref')
    writable_paths: list[str] | None = Field(None, title='Writable Paths')


class ApprovalListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ApprovalSummaryView] = Field(..., title='Items')


class ApprovalRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approval_id: str = Field(..., title='Approval Id')
    approval_type: ApprovalType
    project_id: str = Field(..., title='Project Id')
    reason: str = Field(..., title='Reason')
    requested_at: AwareDatetime | None = Field(None, title='Requested At')
    requested_by: str = Field(..., title='Requested By')
    required_scope: list[str] | None = Field(None, title='Required Scope')
    resolution_payload: ApprovalResolutionPayload | None = None
    resolved_at: AwareDatetime | None = Field(None, title='Resolved At')
    resolved_by: str | None = Field(None, title='Resolved By')
    run_id: str = Field(..., title='Run Id')
    status: ApprovalStatus
    task_id: str = Field(..., title='Task Id')


class ArtifactListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ArtifactView] = Field(..., title='Items')


class AssemblyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_limit: conint(ge=1) | None = Field(3, title='Attempt Limit')
    extra_evidence_refs: list[EvidenceRef] | None = Field(
        None, title='Extra Evidence Refs'
    )
    fact_limit: conint(ge=1) | None = Field(5, title='Fact Limit')
    iteration_id: str | None = Field(None, title='Iteration Id')
    max_blocks_per_level: conint(ge=1) | None = Field(5, title='Max Blocks Per Level')
    memory_limit: conint(ge=1) | None = Field(5, title='Memory Limit')
    namespace_prefix: str | None = Field(None, title='Namespace Prefix')
    project_id: str = Field(..., title='Project Id')
    require_approval: bool | None = Field(True, title='Require Approval')
    secret_broker_enabled: bool | None = Field(False, title='Secret Broker Enabled')
    skills: list[ContextSkill] | None = Field(None, title='Skills')
    task_id: str = Field(..., title='Task Id')
    token_budget: conint(ge=100) | None = Field(4000, title='Token Budget')
    workspace_mode: str | None = Field('read_only', title='Workspace Mode')


class AttemptHistoryReadModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempts: list[AttemptRecord] | None = Field(None, title='Attempts')
    task_id: str = Field(..., title='Task Id')


class AttemptListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[ExecutorAttemptView] = Field(..., title='Items')


class ExecutorInputBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context_blocks: list[ContextBlock] | None = Field(None, title='Context Blocks')
    dispatch: DispatchControl
    evidence_refs: list[EvidenceRef] | None = Field(None, title='Evidence Refs')
    permission_policy: PermissionPolicy
    proposed_commands: list[str] | None = Field(None, title='Proposed Commands')
    schema_version: str | None = Field(
        '2026-04-19.execution.v1', title='Schema Version'
    )
    secret_usages: list[SecretUsage] | None = Field(None, title='Secret Usages')
    task: TaskInfo
    verify_commands: list[VerifyCommand] | None = Field(None, title='Verify Commands')
    workspace: WorkspaceInfo


class ExecutorResultBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifacts: list[ArtifactDescriptor] | None = Field(None, title='Artifacts')
    failure: FailureInfo | None = None
    finished_at: AwareDatetime | None = Field(None, title='Finished At')
    heartbeat_count: int | None = Field(0, title='Heartbeat Count')
    logs: list[LogEntry] | None = Field(None, title='Logs')
    provenance: ExecutionProvenance
    schema_version: str | None = Field(
        '2026-04-19.execution.v1', title='Schema Version'
    )
    started_at: AwareDatetime | None = Field(None, title='Started At')
    status: ExecutionStatus
    verification: VerificationResult | None = None


class IterationListResponse(BaseModel):
    items: list[IterationRecordModel] = Field(..., title='Items')
    schema_version: str | None = Field('2026-04-19.1', title='Schema Version')


class ProjectListResponse(BaseModel):
    items: list[ProjectListItemModel] = Field(..., title='Items')
    pagination: ProjectPaginationModel
    schema_version: str | None = Field('2026-04-19.1', title='Schema Version')


class DispatchExecutionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approval: ApprovalRecord | None = None
    result: ExecutorResultBundle | None = None
